### ISSUE TITLE
File download not working in production

### ISSUE THREAD

**Issue by Fonta22** [Fonta22/iss-locator#14]
The JSON file with the data works in **local**, but not in **production**.

**Comment by Fonta22** [comment]
Thanks @manthanabc !!

**Comment by manthanabc** [comment]
you are welcome : )

**Comment by Fonta22** [comment]
Hey, @manthanabc could you help in https://github.com/Fonta22/iss-locator/issues/30? It is happening the same again and don't really know what to do.

**Comment by manthanabc** [comment]
sure
