### ISSUE TITLE
Fix dark mode button

### ISSUE THREAD

**Issue by Fonta22** [Fonta22/iss-locator#17]
The dark mode **button** should be initially placed as **light**.
![image](https://user-images.githubusercontent.com/61181201/193757363-936bc35e-70ec-4c5c-8166-43819f6d6b13.png)

**Comment by Ajaiqmar** [comment]
@Fonta22, Can you assign me to resolve this issue??

**Comment by Fonta22** [comment]
Sorry @Abdirizaks12, @Ajaiqmar has already done the PR even he should have waited to be assigned, so this is going to be closed. You can check other issues, thanks!
