### ISSUE TITLE
Fix footer date

### ISSUE THREAD

**Issue by developer-diganta** [Fonta22/iss-locator#18]
![image](https://user-images.githubusercontent.com/65999534/193758939-fa103407-1c67-4a6f-a2f8-85bc47b8cc09.png)
The date in the footer can be fixed either using JS or manually. If it seems legit, can I work on it?

**Comment by Fonta22** [comment]
@developer-diganta Sure, but there's already an issue about that! Please comment in https://github.com/Fonta22/iss-locator/issues/16 and I'll assign it 
to you. 👍🏻

**Comment by Fonta22** [comment]
Oh, wait, sorry. Could you explain a bit more what you want to add? @developer-diganta

**Comment by developer-diganta** [comment]
@Fonta22 what I meant was it shows the year as 2021. But since contributions are again starting this year, shouldn't it be 2022?

**Comment by Fonta22** [comment]
Oh, okay, go ahead!

**Comment by developer-diganta** [comment]
Sure! I'll use JS then.

**Comment by Fonta22** [comment]
@developer-diganta as I see, another contributor has already done that, but as I told you to work on it, you can create the file for the function, as it is inside the `index.html` file. So it will count you for the Hacktoberfest!

**Comment by developer-diganta** [comment]
@Fonta22 Thanks!
