### ISSUE TITLE
Linearly interpolate using velocity

### ISSUE THREAD

**Issue by manthanabc** [Fonta22/iss-locator#22]
we can linearly interpolate the aka predict the location between subsequent updates.
this will make the the motion look smooth and should not interfere with the accuracy

**Comment by Fonta22** [comment]
Yo, that would be nice!! If you want to work on it I'll assign you @manthanabc

**Comment by manthanabc** [comment]
that would be great!

**Comment by Fonta22** [comment]
Assigned!
