### ISSUE TITLE
Dark mode for credits bar

### ISSUE THREAD

**Issue by Fonta22** [Fonta22/iss-locator#24]
Make a Dark Mode for the credits bar.
![image](https://user-images.githubusercontent.com/61181201/194038375-29cfd566-b495-408e-84c8-919a115e10c2.png)

**Comment by GeorgeET15** [comment]
Hi, can you assign this to me. Thank you

**Comment by Chaitanya-087** [comment]
i would like to work on this issue

**Comment by Fonta22** [comment]
Since @GeorgeET15 has already done a PR and has been closed, this issue will be assigned to @Chaitanya-087

**Comment by Fonta22** [comment]
PR Merged! Thanks @Chaitanya-087
